version: '{build}'
image: WMF 5

environment:
  #Set to use latest development au version from github
  use_devel_au: $true

  #Github token to commit pushed packages to repository
  github_user_repo: majkinetor/chocolatey
  github_api_key:
    secure: 5/3TZtHT4M8984tJhsFyLST+e/JDpc8ia871UD4hv3dD2+Kb+xnaB4wMH1WloDD1

  #Gmail credentials - for error notifications
  mail_user: majkinetor@gmail.com
  mail_pass:
    secure: h/+9+co89yapWdXBYYXJvPQQvViVRRq1zd2Us0aTSjY=

  #ID of the gist used to save run results
  gist_id: 181b18886fdd363158064baf817fa2ff

  #Chocolatey API key - to push updated packages
  api_key:
    secure: Zaby8iZHam4NMZ4AAjH/ZM19D+soKoohnHnRAcusk/HvNkEPMA8Wd3jxUGPnQgPJ

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- ps: |
    if ($Env:use_devel_au) {
        cd c:/projects
        git clone https://github.com/majkinetor/au.git
        cd au
        git fetch
        git checkout integrate
        ./build.ps1 -Install
    } else {
        Install-PackageProvider -Name NuGet -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        Install-Module au
        Get-Module au -ListAvailable | select Name, Version
    }

build_script:
- ps: |
    ./update_all.ps1

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

