version: '{build}'
image: WMF 5

install:
- gem install gist
- ps: |
    Install-PackageProvider -Name NuGet -Force
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
    Install-Module au

build_script:
- ps: c:/projects/chocolatey/update_all.ps1

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
- provider: Email
  to: miodrag.milic@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

environment:
  gist_id: 181b18886fdd363158064baf817fa2ff
  github_pass:
    secure: MLLwE43J/DaZdfFcWWugSw==
  mail_pass:
    secure: BJGlZo/cyaxwcqaQsu/nQxopDo3Y6hk1iMMQtpcw4YA=Zaby8iZHam4NMZ4AAjH/ZM19D+soKoohnHnRAcusk/HvNkEPMA8Wd3jxUGPnQgPJ
  api_key:
    secure: Zaby8iZHam4NMZ4AAjH/ZM19D+soKoohnHnRAcusk/HvNkEPMA8Wd3jxUGPnQgPJ
