version: '{build}'
max_jobs: 1
image: WMF 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  #Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version: master
  au_push: true

  #Github token to commit pushed packages to repository
  github_user_repo: majkinetor/chocolatey
  github_api_key:
    secure: 5/3TZtHT4M8984tJhsFyLST+e/JDpc8ia871UD4hv3dD2+Kb+xnaB4wMH1WloDD1

  github_username: majkinetor
  github_password:
    secure: MLLwE43J/DaZdfFcWWugSw==

  #Gmail credentials - for error notifications
  mail_user: majkinetor@gmail.com
  mail_pass:
    secure: h/+9+co89yapWdXBYYXJvPQQvViVRRq1zd2Us0aTSjY=

  #ID of the gist used to save run results
  gist_id: a700c70b8847b29ebb1c918d47ee4eb1

  #Chocolatey API key - to push updated packages
  api_key:
    secure: Zaby8iZHam4NMZ4AAjH/ZM19D+soKoohnHnRAcusk/HvNkEPMA8Wd3jxUGPnQgPJ

init:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey AU"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- ps: |
    $x=$null; $is_branch = ($Env:au_version -ne $null) -and ([version]::TryParse($Env:au_version, [ref]$x) -eq $false)
    if ($is_branch) {
        pushd ..
            git clone -q https://github.com/majkinetor/au.git
            cd au
            git fetch
            git checkout -q $Env:au_version
            ./build.ps1 -Install -NoChocoPackage
        popd
    } else {
        Install-PackageProvider -Name NuGet -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

        $params = @{ Name = 'au' }
        if ( $Env:au_version -ne $null ) { $params.Version = $Env:au_version }
        Install-Module @params

        Get-Module au -ListAvailable | select Name, Version
    }

build_script:
- ps: |
    ./update_all.ps1

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

