version: '{build}'
image: WMF 5

environment:
  #Github credentials - used to save result to gist and to commit pushed packages to the git repository
  github_user: majkinetor
  github_pass:
    secure: MLLwE43J/DaZdfFcWWugSw==

  #Gmail credentials - for error notifications
  mail_user: majkinetor@gmail.com
  mail_pass:
    secure: h/+9+co89yapWdXBYYXJvPQQvViVRRq1zd2Us0aTSjY=

  #ID of the gist used to save run results
  gist_id: 181b18886fdd363158064baf817fa2ff

  #Chocolatey API key - to push updated packages
  api_key:
    secure: Zaby8iZHam4NMZ4AAjH/ZM19D+soKoohnHnRAcusk/HvNkEPMA8Wd3jxUGPnQgPJ

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- gem install gist --no-ri --no-rdoc
- "ruby -e \"require 'gist'; Gist.login! username: ENV['github_user'], password: ENV['github_pass'] if ENV['github_user'] \""
- ps: |
    "machine github.com`nlogin $Env:github_user`npassword $Env:github_pass" | Out-File ~/_netrc
    Install-PackageProvider -Name NuGet -Force
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
    Install-Module au
    Get-Module au -ListAvailable | select Name, Version

build_script:
- ps: c:/projects/chocolatey/update_all.ps1

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: update_info.xml
- path: gist.md

notifications:
- provider: Email
  to: majkinetor@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

